### ISSUE TITLE
RuntimeError: 'weight' must be 2-D

### ISSUE THREAD

**Issue by haogegege666** [newlei/FDA#1]
运行代码出现问题
File "C:\\paper_code\FDA-main\fda_bpr_ml\main.py", line 133, in forward
    gender = F.embedding(u_batch, self.users_features)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 2199, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: 'weight' must be 2-D

**Comment by newlei** [comment]
可以提供更多信息吗？我这边下载代码，重新跑了一遍是没有问题的

**Comment by newlei** [comment]
查到了如果是高版本的pytorch会出现上述问题，解决方案如下：

```
gender = F.embedding(u_batch,self.users_features)
male_gender = gender.type(torch.BoolTensor)
female_gender = (1-gender).type(torch.BoolTensor)
```
将上述代码替换为下面的就可以解决问题了
```
gender = F.embedding(u_batch,torch.unsqueeze(self.users_features,1)).reshape(-1)
male_gender = gender.type(torch.BoolTensor).cuda()
female_gender = (1-gender).type(torch.BoolTensor).cuda()        
```

**Comment by haogegege666** [comment]
好的感谢 问题已解决
